/*
 * HairSalon: Scheduling and Management System
 * Systems II - Southern Alberta Institute of Technology
 * 
 * File Author: Philippe Durand
 * 
 * System Developed by:
 * Joey Ren, Philippe Durand, Miyoung Han, Horace Wan and Nuha Bazara
 */
package hs.objects;

import java.util.*;

/**
 * This bean holds alert information that is generated by the system when
 * certain events occur from inventory or scheduling components.
 * 
 * @author Philippe Durand
 */
public class AlertBean extends DataBean implements Comparable
{
	/**
	 * The date the alert was created on.
	 */
	private Date date = null;
	/**
	 * The message that the alert presents to the employees.
	 */
	private String message = null;
	/**
	 * The type of alert this is being generated.
	 */
	private String type = null;
	/**
	 * The link that the message link will take the employee to if clicked.
	 */
	private String link = null;
	/**
	 * The level of importance of the bean.
	 */
	private String level = null;
	/**
	 * The identification number of the record that caused the alert.
	 */
	private Integer recordNo = null;
	/**
	 * The identification number of the alert.
	 */
	private Integer alertNo = null;

	/**
	 *  Default constructor for alert bean.
	 */
	public AlertBean ()
	{
	}

	public Integer getRecordNo ()
	{
		return recordNo;
	}

	public void setRecordNo (Integer recordNo)
	{
		this.recordNo = recordNo;
	}

	public String getType ()
	{
		return type;
	}

	public void setType (String type)
	{
		this.type = type;
	}

	public Integer getAlertNo ()
	{
		return alertNo;
	}

	public void setAlertNo (Integer alertNo)
	{
		this.alertNo = alertNo;
	}

	public Date getDate ()
	{
		return date;
	}

	public void setDate (Date date)
	{
		this.date = date;
	}

	public String getLevel ()
	{
		return level;
	}

	public void setLevel (String level)
	{
		this.level = level;
	}

	public String getLink ()
	{
		return link;
	}

	public void setLink (String link)
	{
		this.link = link;
	}

	public String getMessage ()
	{
		return message;
	}

	public void setMessage (String message)
	{
		this.message = message;
	}

	public int compareTo (Object o)
	{
		AlertBean a = (AlertBean) o;

		return (getAlertNo ().compareTo (a.getAlertNo ()));
	}

	@Override
	public boolean equals (Object o)
	{
		AlertBean a = (AlertBean) o;

		boolean result1 = a.getAlertNo ().equals (this.getAlertNo ());

		return (result1);
	}

	@Override
	public int hashCode ()
	{
		int hash = 7;
		hash = 29 * hash + (this.alertNo != null ? this.alertNo.hashCode () : 0);
		return hash;
	}
}

